version: '3.8'

services:
  neo4j:
    image: neo4j:5.13.0
    container_name: eufy-seo-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/var/lib/neo4j/import
      - ./db/plugins:/plugins
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/eufyseo2024
      
      # Memory configuration
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      
      # Enable APOC procedures
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      
      # Database settings
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      
      # Allow upgrade
      - NEO4J_dbms_allow__upgrade=true
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  neo4j-init:
    image: neo4j:5.13.0
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: >
      sh -c "
        echo 'Waiting for Neo4j to be ready...';
        sleep 10;
        echo 'Neo4j is ready. You can now run the import script.';
      "
    profiles:
      - init

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
